### PR TITLE
Regenerate site 2020-12-21 vs nut commit 46c7da76 ...

### PR DESCRIPTION
**Pull request by jimklimov**
Follows up from #1 to bump documentation and other contents on the NUT web site to match current master branch state.

There are several changes to content, all automated but still were worth classifying into separate commits:
* Regeneration of files that were committed previously
* Initial commits of new docs, protocols and ddl entries
* Initial commits of `index.html` files in many (all?) subdirectories that were not in Git before - to me this is the most questionable change, whether these indexes are needed and/or would not break the site somehow.

Another questionable aspect is whether we accept publishing technical content on NUT website which should match the current master branch codebase, but step away from the latest published release. I can understand arguments for both approaches :) 

I do hope we will have a release in tangible future so the point will become moot... for some time. But generally the question remains and would revive as soon as we make a next commit in the master after a release. Maybe it makes sense to maintain two sites (for latest release and for tracking the Git HEADs of repositories involved, maybe even automatically).

### CODE REVIEW

**Comment by jimklimov** [comment]
Note: if I read that right, the missing indexes were a noted problem at https://github.com/networkupstools/nut/issues/566 and https://github.com/networkupstools/nut-website/issues/19

It may be worthwhile to cherry-pick the generated indexes without a full 2.7.4-vs-master rematch of the website, in a separate PR to address those issues.

**Comment by clepple** [comment]
> Regeneration of files that were committed previously

I did see some commits for DDL entries here. However, they look like they apply to 2.7.4, so that should be okay.

Some of the generated HTML files for developer man pages have a new "Last updated" date of 2017 and a version number of 2.7.4.1 - unclear what is needed to bump them to 2020 dates. Not a show-stopper, IMHO.

> Initial commits of new docs, protocols and ddl entries

I didn't review docs and protocols, but that sounds good to me.

A few DDL entries are refer to code that isn't released except in git HEAD:
* APC ATS AP7724: https://github.com/networkupstools/nut/issues/260 (new MIB file)
* APC SmartUPS C1500: https://github.com/networkupstools/nut/issues/359 (should not be different from 2.7.4, though)
* Eaton 5E: https://github.com/networkupstools/nut/issues/335 (also not much difference from 2.7.4?)
* Raritan PX2-1486: SNMP MIB introduced in networkupstools/nut@cc63de084424b64ed394081604bc4ce0ed83a945 

This seems reasonable.

> Initial commits of index.html files in many (all?) subdirectories that were not in Git before - to me this is the most questionable change, whether these indexes are needed and/or would not break the site somehow.

I don't know how they would break the site - everything else except the root URL references specific HTML files, so this seems like it could only improve things.

> Maybe it makes sense to maintain two sites (for latest release and for tracking the Git HEADs of repositories involved, maybe even automatically).

This was my intent with http://new.networkupstools.org vs https://networkupstools.org - updates to nut-website would be available in draft form at new.n.o from a Buildbot builder. However, I ran into several issues:

* resource constraints prevented the Buildbot master from being directly on the interwebs, which meant a fragile proxy scheme. This seems to still work for new.n.o but not for the autogenerated release tarballs.
* rebuilding the website when the main NUT repository changed meant that I had to update a Git submodule manually on a throwaway branch (or script it), and I punted on the automation.

I really don't have time to fix the NUT Buildbot setup - I would consider it a dead end. It is also not well isolated from my development machines (hence why it only builds tags and branches created by NUT developers, not random pull requests), so I can't just hand over the keys to someone else to take it over. It is based on an old, unsupported version of Buildbot, thus it is likely only good for lessons-learned. Many of those could apply to a GitHub Actions automation scheme, if someone were so inclined. I realize this is bad timing with the current questions about Travis CI.org/.com, so I am not shutting Buildbot down yet.

**Review by clepple — APPROVED** [review]
LGTM (see longer comment in main conversation)

**Comment by jimklimov** [comment]
Experimenting now with a separate repository enabled for github pages, which currently works as https://networkupstools.org/networkupstools-master.github.io/index.html (updated with this PR's content and then some more, to current NUT and DDL master branch data).

It seems that GHP is limited to allow only one repo (named exactly as `orgname`.github.io) to serve as the "root" site, but happens to let other repos serve as sub-sites. But maybe just the updated DNS names take a while to roll out into the internet so I'll see better tomorrow or later, if I can make the intended https://master.networkupstools.org to work smoothly this way. In the worst case, can redirect to this URL, and we can rename it from "networkupstools-master.github.io" to something less clumsy if nothing else works, and serve as the sub-namespaced site.

**Pull request closed without merging**
